- name: libevent-devel
  yum:
    name: libevent-devel.x86_64
    state: present
- name: Mesos 1.1.0
  yum:
    name: http://repos.mesosphere.com/el/7/x86_64/RPMS/mesos-1.1.0-2.0.107.centos701406.x86_64.rpm
    state: present


