# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.define "mesos1" do |mesos1|
		mesos1.vm.box = "ubuntu/xenial64"
		mesos1.vm.network "public_network", ip: "192.168.1.150", bridge: "enp6s0"
		mesos1.vm.hostname = "mesos1"
		mesos1.vm.provision "shell", path: "install-docker.sh"
	end

	config.vm.define "mesos2" do |mesos2|
		mesos2.vm.box = "ubuntu/xenial64"
		mesos2.vm.network "public_network", ip: "192.168.1.151", bridge: "enp6s0"
		mesos2.vm.hostname = "mesos2"
		mesos2.vm.provision "shell", path: "install-docker.sh"
	end

	config.vm.define "mesos3" do |mesos3|
		mesos3.vm.box = "ubuntu/xenial64"
		mesos3.vm.network "public_network", ip: "192.168.1.152", bridge: "enp6s0"
		mesos3.vm.hostname = "mesos3"
		mesos3.vm.provision "shell", path: "install-docker.sh"
	end

	config.vm.define "mesos4" do |mesos4|
		mesos4.vm.box = "ubuntu/xenial64"
		mesos4.vm.network "public_network", ip: "192.168.1.153", bridge: "enp6s0"
		mesos4.vm.hostname = "mesos4"
		mesos4.vm.provision "shell", path: "install-docker.sh"
	end

end
