# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.box = "timwebster9/rhel73"
	config.vm.network "private_network", ip: "192.168.56.10"
	config.vm.hostname = "enterpriselinux"

	config.vm.provider "virtualbox" do |v|
		  v.memory = 2048
		  v.cpus = 2
	end

	# Workaround for possible Vagrant bug where host-only network interface doesn't come up
	config.vm.provision "shell", inline: "systemctl restart network"

	# Activate RH subscription - change to use your credentials
	config.vm.provision "shell", inline: "subscription-manager register --username <username> --password <password> --auto-attach"

	# Add extra repos needed for Mesos dependencies
	config.vm.provision "shell", inline: "subscription-manager repos --enable rhel-7-server-optional-rpms"

	config.vm.provision "ansible_local" do |ansible|
		ansible.verbose = "v"
		ansible.playbook = "provisioning/playbook.yml"
	end

end
