# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.box = "timwebster9/rhel73"
	config.vm.network "private_network", ip: "192.168.56.10"
	config.vm.hostname = "rhel"

	config.vm.provider "virtualbox" do |v|
		  v.memory = 4096
		  v.cpus = 2
	end

	config.vm.provision "ansible_local" do |ansible|
		ansible.verbose = "v"
		ansible.playbook = "provisioning/playbook.yml"
	end

end
